version: v1.0.2
flow:

  host:
  port:
  saydo:
  closedfo:

vad:
  speech_timeout: 300   #to active state. By default, 300 (ms)
  silence_timeout: 300 #to inactive state. By default, 300 (ms)
  noinput_timeout: 5000  #NoinputTimeout is no input timeout. By default, 5000 (ms)
  noinput_timers: true #NoinputTimers is a flag indicates if noinput timer is on. By default, true
  recognition_timeout: 2000 #RecognitionTimeout is recognition timeout. By default, 20000 (ms)
  recognition_timers: true #RecognitionTimers is a flag indicates if recognition timer is on. By default, true
  vad_level: 3 #VADLevel is the aggressiveness mode for vad. By default, 3 for anti background noise
  sample_rate: 8000 #It only supports 8000 and 16000
  sample_bytes: 2 #BytesPerSample defines bytes per sample for linear pcm
  frame_duration: 20 # It should be 10ms, 20ms or 30ms. By default, 20 (ms).
  multiple: false #false is for processing a incoming voice stream.
